import React from "react"

export const COLORS = {
    
    PRIMARY_COLORS_FIRST: '#F77F00',
    PRIMARY_COLORS_SECOND: '#CB6800',
    PRIMARY_COLORS_THIRD: '#FFD4A6',
    SECONDARY_COLORS_FIRST: '#FCBF49',
    SECONDARY_COLORS_SECOND: '#E9BD69',
    SECONDARY_COLORS_THIRD: '#FFEDC9',
    WARNING_COLORS_FIRST: '#F12929',
    WARNING_COLORS_SECOND: '#D24B4B',
    TEXT_COLORS_FIRST: '#323338',
    TEXT_COLORS_SECOND: '#F77F00',
    TEXT_COLORS_THIRD: '#FFFFFF',
    TEXT_COLORS_DISABLED : '#948EA5',
    BACKGROUND_COLORS_FIRST: '#F5F5F5',
    BACKGROUND_COLORS_SECOND: '#E4E3E8',
    OTHER_COLORS: '#00C48C',
   }

export const FONTSIZE = {
    H1_LOGO_HEADING: 64,
    H2_MAIN_HEADING: 32,
    H3_SECONDARY_TITLE: 24,
    H4_PARAGRAPH_HEADING: 16,
    H5_INPUT_TITLE: 14,
    BODY_TEXT: 14,
    INPUT_PROMPT: 12,
   }

export const FONTWEIGHT = {
    LOGO_HEADING: '700',
    MAIN_HEADING: '700',
    SECONDARY_TITLE: '600',
    PARAGRAPH_HEADING: '500',
    INPUT_TITLE: '400',
    BODY_TEXT: '300',
    INPUT_PROMPT: '200',
   } as any

export const SIZE = {
    LARGE_WIDTH: 347,
    SMALL_WIDTH: 157,
    HEIGHT: 48,
}

export const FONTFAMILY = {
    SF_PRO: 'SF-PRO',
    WICKED_MOUSE: 'Wicked-Mouse',
 
}

